### ISSUE TITLE
File size limit is not obeyed when using chunking

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_antivirus#179]
files of any size get checked regardless of the "File size limit" setting when chunking is used

**Comment by PVince81** [comment]
I don't think this is a release blocker -> p2

cc @pmaier1 @felixboehm if you think otherwise

**Comment by PVince81** [comment]
which chunking ? old webdav chunking or new dav endpoint chunking ? (the latter is with the "uploads/" folder)

Antivirus might need a similar approach like firewall to find out the final file size

**Comment by individual-it** [comment]
chunking on both dav endpoints does not calculate the size correctly

**Comment by VicDeo** [comment]
@individual-it With  which app version?

**Comment by VicDeo** [comment]
<img width="476" alt="limit-v0 10 1 0" src="https://user-images.githubusercontent.com/991300/30037474-cf9f0750-91c3-11e7-8d83-23885aee8ff1.png">

**Comment by individual-it** [comment]
> @individual-it With which app version?

current master branch

**Comment by PVince81** [comment]
moving to development, to look into for the next release @VicDeo

**Comment by PVince81** [comment]
will this need core changes ?

**Comment by PVince81** [comment]
will this need core changes ? can we move forward with this ?

**Comment by VicDeo** [comment]
Fixed with https://github.com/owncloud/files_antivirus/pull/196

**Comment by individual-it** [comment]
reopening as I still have the problem in 0.12.0
reproduce: 
1. set "File size limit" to 100bytes
2. try to upload `eicat_com.zip` (184byte) by chunking e.g.:
```
$ curl --user $user:$pwd http://$host/$path/remote.php/dav/uploads/$user/12345/1 --request PUT --data-binary "@eicar_com.zip_01"
$ curl --user $user:$pwd http://$host/$path/remote.php/dav/uploads/$user/12345/2 --request PUT --data-binary "@eicar_com.zip_02"
$ curl --user $user:$pwd http://$host/$path/remote.php/dav/uploads/$user/12345/3 --request PUT --data-binary "@eicar_com.zip_03"
$ curl --user $user:$pwd http://$host/$path/remote.php/dav/uploads/$user/12345/.file --request MOVE -H "Destination: http://$host/$path/remote.php/dav/files/$user/virus"
```

**Comment by felixboehm** [comment]
@VicDeo please retest, and provide a fix

**Comment by VicDeo** [comment]
I don't see a solution without refactoring the app. 

An app catches a call to `fopen` and makes a decision on the filesystem level.
 fopen is not aware about the source of the data and a target file has zero size at that moment. 
Let me dig more...

**Comment by VicDeo** [comment]
hm. Given that chunking requires an `OC-Total-Length` header for the final MOVE I wonder if the size check is broken in core...
https://github.com/owncloud/core/blob/master/apps/dav/lib/Upload/ChunkingPlugin.php#L98-L107

According to this snippet
```
$ curl --user $user:$pwd http://$host/$path/remote.php/dav/uploads/$user/12345/.file --request MOVE -H "Destination: http://$host/$path/remote.php/dav/files/$user/virus"
```
is incorrect and
```
$ curl --user $user:$pwd http://$host/$path/remote.php/dav/uploads/$user/12345/.file --request MOVE -H "Destination: http://$host/$path/remote.php/dav/files/$user/virus" -H "OC-Total-Length: 184" 
```
is needed

**Comment by VicDeo** [comment]
oops. it is allowed to omit `OC-Total-Length`. Please disregard the previous comment.
